services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: budget_app
    working_dir: /var/www/html
    volumes:
      - ./app:/var/www/html
      - ./app/storage:/var/www/html/storage
    environment:
      APP_ENV: local
      APP_URL: http://localhost:8000

      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: budget
      DB_USERNAME: app
      DB_PASSWORD: secret

      QUEUE_CONNECTION: database
      OLLAMA_URL: http://ollama:11434
    depends_on:
      - db
    command: composer run dev
    ports:
      - "8000:8000"   # Laravel
      - "5173:5173"   # Vite HMR

  queue:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: budget_queue
    working_dir: /var/www/html
    volumes:
      - ./app:/var/www/html
      - ./app/storage:/var/www/html/storage
    environment:
      APP_ENV: local
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: budget
      DB_USERNAME: app
      DB_PASSWORD: secret
      QUEUE_CONNECTION: database
      OLLAMA_URL: http://ollama:11434
    depends_on:
      - db
    command: php artisan queue:work --tries=3 --timeout=120

  db:
    image: mysql:8.0
    container_name: budget_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: budget
      MYSQL_USER: app
      MYSQL_PASSWORD: secret
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  dbdata:
